### ISSUE TITLE
Trouble working with form data structure

### ISSUE THREAD

**Issue by davalb** [mathielen/sapoci#2]
I am trying to render the form, but I have a little trouble with the structure of the data. I am using the example from the `OciFactoryFormBuilderTest.php`. When I output `$form->getData()`, I get this:

    Array
    (
        [NEW_ITEM-DESCRIPTION] => Array
            (
                [1] => description
            )
        [NEW_ITEM-LONGTEXT_1:132] => Array
            (
                [0] => longtext
            )
        [NEW_ITEM-TAX] => Array
            (
                [1] => 19
            )
    )

The problem I am facing is that the values are in arrays and that the keys are not consistenly 0, but sometimes 1. What is the official way to get a value from the form? I guess I could do this `array_values($form->get('NEW_ITEM-DESCRIPTION')->getData())[0]` to get the description, but this is really ugly.

**Comment by mathielen** [comment]
This, unfortunately is indeed intended. It seems very wrong and strange but in fact it is the correct OCI behavior.

1. Any field (like tax) is a list of values as per order line. So the tax of the first line in the order is defined in field NEW_ITEM-TAX[1].
2. The line counter starts with 1 (instead of 0 which would be more natural)
3. There is one exception with this strange logic. That is: the LONGTEXT field. Here the array-position-line-logic above is not intended. Instead the line-identifier goes within the fieldname. So line 1 is NEW_ITEM-LONGTEXT_1:132. Line 2 is NEW_ITEM-LONGTEXT_2:132. The value should not be an array but a plain string. Also, note the ":132" suffix. That is intended as well.

Sorry - but OCI is indeed VERY ugly!

**Comment by davalb** [comment]
Thanks for the info, that is good to know. Do you know what the :132 suffix stands for?
