### ISSUE TITLE
Longtext fields

### ISSUE THREAD

**Issue by Thorry84** [mathielen/sapoci#5]
As we all know the way the longtext fields are defined by the standard is crazy with the line number in the fieldname and the :132 added. But even stranger, the field itself should be a collection, even though it can only have a single value.

But I've recently got into a discussion with a partner implementing the OCI from the receiving end. We currently submit the longtext of the first line in the field NEW_ITEM-LONGTEXT_1:132[0], but the specs say the fieldname should be NEW_ITEM-LONGTEXT_n:132[]. The discussion is about the 0, which shouldn't really matter, but might be out of specs?

What are your thoughts on this? Should the 0 be included in the fieldname? Does it matter?

Thanks in advance! I hate OCI man...

**Comment by mathielen** [comment]
Hey @Thorry84 

Thanks for reaching out.
We use the library for various integrations into big corporate procurement systems without problems. So, I would say it doesnt matter. If you experience otherwise please let me know.

Best regards,
Markus

P.S. Yeah, OCI is really an adorable interface definition :D
